products:
    - banana:
        id: '275280804'
        aliases:
            - bananas
    - cherry tomatoes:
        id: '285212132'
    - milk:
        id: '260569996'
    - plums:
        id: '292275580'
    - strawberries:
        id: '272202380'
    - raspberries:
        id: '2873776670'
    - blueberries:
        id: '292248554'
    - kiwi:
        id: '256644151'
        aliases:
            - kiwis
    - mango:
        id: '255805844'
        aliases:
            - mangoes
    - carrot:
        id: '254638565'
    - parsnip:
        id: '253557408'
    - butternut squash:
        id: '277492902'
    - courgette:
        id: '253554596'
    - mushrooms:
        id: '273796618'
    - new potatoes:
        id: '266125635'
    - maris piper potatoes:
        id: '258423755'
    - avocados:
        id: '256074560'
        aliases:
            - avocado
    - salad:
        id: '293172353'
    - hummus:
        id: '260084012'
    - butter:
        id: '254263685'
    - eggs:
        id: '250802567'
        aliases:
            - egg
    - cheddar:
        id: '277925449'
        aliases:
            - cheese
    - mozzarella:
        id: '268328438'
    - feta:
        id: '260671607'
    - halloumi:
        id: '264245536'
    - chicken:
        id: '292285280'
    - turkey:
        id: '266507796'
    - mince beef:
        id: '250871426'
    - salmon:
        id: '288730236'
    - tortelloni:
        id: '274737066'
    - prosciutto:
        id: '267533853'
    - bread:
        id: '279505857'
    - wraps:
        id: '261092202'
    - piada:
        id: '287487865'
        aliases:
            - piadina
    - panettone:
        id: '279422649'
    - tuna:
        id: '275975438'
    - artichokes:
        id: '273716594'
    - yoghurt cereal bars:
        id: '271099738'
    - cinnamon cereal bars:
        id: '289661673'
    - apple and strawberry cereal bars:
        id: '275504444'
    - apple crumble cereal bars:
        id: '285355149'
    - granola cereal bars:
        id: '268069030'
    - sunflower oil:
        id: '254918228'
    - green pesto:
        id: '254879319'
        aliases:
            - pesto
    - thai green curry paste:
        id: '261105536'
    - fusilli:
        id: '255343007'
    - spaghetti:
        id: '254878424'
    - basmati rice:
        id: '251442449'
    - peanut butter:
        id: '259433753'
    - coconut milk:
        id: '261626649'
    - fish fingers:
        id: '268202034'
    - spinach:
        id: '282489773'
    - vegetarian chicken dippers:
        id: '250085585'
        aliases:
            - quorn chicken dippers
            - fake chicken dippers
    - vegetarian chicken pieces:
        id: '266244436'
        aliases:
            - quorn chicken pieces
            - fake chicken pieces
    - vegetarian meatballs:
        id: '277473303'
    - vegetarian mince:
        id: '257974340'
    - coke:
        id: '282843066'
        aliases:
            - coca cola
    - orange juice:
        id: '258853885'
    - water:
        id: '260487031'
    - lemon ice tea:
        id: '253398763'
    - peach ice tea:
        id: '253398861'
    - aperol:
        id: '278480235'
    - toothbrush:
        id: '259488941'
    - toothpaste:
        id: '254550506'
    - mens deodorant:
        id: '272227552'
        aliases:
            - Roberto's deodorant
    - womens deodorant:
        id: '271327850'
        aliases:
            - Jenny's deodorant
    - ibuprofen:
        id: '254434437'
    - paracetamol:
        id: '255488740'
