products:
    - banana:
        id: '275280804'
        aliases:
            - bananas
    - cherry tomatoes:
        id: '285212132'
    - milk:
        id: '260569996'
    - plums:
        id: '292275580'
    - strawberries:
        id: '272202380'
    - raspberries:
        id: '2873776670'
    - blueberries:
        id: '292248554'

